[package]
name = "pamonitor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulse = { version = "2.0", package = "libpulse-binding" }
futures = "0.3.16"
